CREATE PROCEDURE IF NOT EXISTS create_products_table()
BEGIN
    CREATE TABLE IF NOT EXISTS Products (
        Id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,  
        Naam VARCHAR(255) NOT NULL,  
        Barcode VARCHAR(255) NOT NULL UNIQUE,  
        IsActive BIT NOT NULL DEFAULT 1,  
        CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
        UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  
    ) ENGINE=InnoDB;
END;

